"""Narration segmentation for the Masaryk University exchange video.

Each scene is generated as ONE TTS request (same voice, same style, same seed)
so the voice stays continuous inside a scene. Lines are the breathing units:

  tts    text actually sent to TTS. Numbers and foreign names are spelled
         in Hangul here only (pronunciation control); the screen always
         uses the original spelling.
  pause  pause AFTER the line. C = comma breath (natural, clamped short)
         S = 0.15-0.30s  M = 0.40-0.70s  L = 0.80-1.20s  X = ~1.2s (result)
         P = paragraph break inside an info block (~0.75s)
         Q = long pause whose TTS tag is only "medium" (the model fills
             long-pause tags with performed sighs in tense passages)
  cues   {cue_id: (anchor, visual)}; anchor is a substring of tts whose
         spoken onset fires the visual. "anchor|end" fires at the word end.

Run:  python segments.py  -> writes segments.json
"""
import json, os

STYLE = (
    "Korean native male narrator in his late 20s to early 30s. Calm, warm, natural and "
    "conversational, confident and polished, like a thoughtful young Korean man calmly "
    "telling his own exchange-student story in a well-produced documentary-style YouTube "
    "video. Moderate and consistent pace. Natural Seoul-standard Korean prosody, natural "
    "breathing, subtle emotional variation. Not an announcer voice, not an exaggerated "
    "commercial voice, no robotic rhythm, no sudden speed changes. Foreign proper nouns are "
    "pronounced naturally inside Korean sentences, without an exaggerated English accent."
)

VOICE = {
    "model": "gemini-3.8-flash-tts",
    "voice": "Iapetus",
    "languageCode": "ko-KR",
    "temperature": 1.0,
    "seed": 7,
    "style": STYLE,
}

# pause targets in seconds (min, target, max) applied after TTS on line boundaries
PAUSES = {
    "C": (0.08, 0.18, 0.32),
    "S": (0.18, 0.26, 0.34),
    "M": (0.42, 0.55, 0.70),
    "L": (0.85, 1.00, 1.20),
    "P": (0.62, 0.72, 0.78),   # paragraph break inside an information block
    "Q": (0.85, 1.00, 1.20),   # long pause, but TTS only gets a medium tag (avoids performed sighs)
    "X": (1.15, 1.25, 1.35),
}
# inline tag sent to TTS so the model also *performs* the breath
TTS_TAG = {"C": "", "S": "", "M": " [medium pause]", "L": " [long pause]", "P": " [long pause]", "Q": " [medium pause]", "X": " [long pause]"}

PRONUNCIATION = {
    "Masaryk University": "마사릭 유니버시티",
    "IELTS": "아이엘츠",
    "Academic Calendar": "아카데믹 캘린더",
    "QS Ranking": "큐에스 랭킹",
    "IE University": "아이이 유니버시티",
    "Vrije Universiteit Amsterdam": "브레이어 유니버시테이트 암스테르담",
    "LMU": "엘엠유",
    "Frankfurt University of Applied Sciences": "프랑크푸르트 유니버시티 오브 어플라이드 사이언스",
    "Free University of Berlin": "프리 유니버시티 오브 베를린",
    "Sheffield": "셰필드",
    "Brno": "브르노",
    "24학번": "이사 학번",
    "2027년 1학기": "이천이십칠 년 일 학기",
    "218개": "이백십팔 개",
    "4.33": "사 점 삼삼",
    "8.0": "팔 점 영",
    "10명 → 1명": "열 명 → 한 명",
    "2명 / 6명": "두 명 / 여섯 명",
    "1지망": "일 지망",
}

def L(tts, pause="S", **cues):
    return {"tts": tts, "pause": pause, "cues": cues}

SCENES = [
  # ------------------------------------------------------------------ 01
  {"id": "s01", "title": "OPENING", "theme": "dark", "lead": 1.6, "tail": 2.4,
   "lines": [
    L("안녕하세요.", "M", hello=("안녕", "map drifts in from black")),
    L("이천이십칠 년 일 학기, 저는 체코의 마사릭 유니버시티로 교환학생을 가게 됐습니다.", "M",
      czech=("체코의", "camera glides to Czechia"),
      brno=("마사릭", "Brno pin + MASARYK UNIVERSITY label")),
    L("그런데 사실, 처음부터 이 학교를 정해놓고 준비했던 건 아닙니다.", "M",
      pullback=("그런데", "label fades, camera pulls back to Europe"),
      cities=("처음부터", "London→Berlin→Amsterdam→Madrid→Prague pins + arcs")),
    L("성균관대학교에서 지원할 수 있는 교환교만, 무려 이백십팔 개.", "M",
      skku=("성균관대학교", "Seoul origin tag"),
      n218=("이백십팔", "218 dots + counter 0→218"),
      n218end=("이백십팔 개|end", "counter lands on 218")),
    L("그래서 저는 일 년 넘게, 정말 많은 학교를 비교했습니다.", "M",
      year=("일 년", "1 YEAR+ tag"),
      compare=("비교했습니다", "dots linked pairwise (comparison)")),
    L("오늘은 그 과정에서, 어떤 기준으로 학교를 골랐는지,", "S",
      ag1=("어떤 기준으로", "agenda 01 CRITERIA")),
    L("왜 결국 마사릭 유니버시티를 선택했는지,", "S",
      ag2=("마사릭", "agenda 02 WHY MASARYK")),
    L("그리고 실제 지원 과정에서 느낀 팁까지 이야기해보겠습니다.", "X",
      ag3=("팁까지", "agenda 03 TIPS"),
      title=("이야기해보겠습니다|end", "agenda clears; MASARYK UNIVERSITY / BRNO, CZECH REPUBLIC title")),
   ]},
  # ------------------------------------------------------------------ 02
  {"id": "s02", "title": "MY SITUATION", "theme": "light", "lead": 1.0, "tail": 1.0,
   "lines": [
    L("저는 성균관대학교 이사 학번이고,", "S",
      skku=("성균관대학교", "node 2024 SKKU (logo)"),
      y2024=("이사 학번", "year label 2024 · 입학")),
    L("일 학년을 마친 뒤, 두 개 학기를 수료하고 군 입대를 했습니다.", "M",
      sem=("두 개 학기", "node 2 SEMESTERS"),
      mil=("군 입대", "node 2025 MILITARY SERVICE")),
    L("그리고 이천이십육 년 시월, 전역을 앞두고 있습니다.", "M",
      dis=("이천이십육", "node 2026.10 DISCHARGE")),
    L("군 입대 전부터, 전역하고 바로 학교로 돌아가기보다는,", "S",
      back=("바로 학교로", "dashed default path → SKKU")),
    L("한 번쯤 해외에서 살아보고 싶다는 생각이 있었습니다.", "M",
      abroad=("해외에서", "branch to 2027.01 EXCHANGE STUDENT")),
    L("특히 군 생활을 하면서, 그 마음은 더 커졌습니다.", "M",
      grow=("더 커졌습니다", "exchange node grows")),
    L("조금 더 넓은 세상으로 나가서,", "S",
      wide=("넓은 세상", "ripple expands outward")),
    L("새로운 환경에서 살아보고 싶었습니다.", "M"),
    L("지원 당시 제 성적은,", "S",
      stats=("지원 당시", "timeline recedes; stat panel")),
    L("학점 사 점 삼삼.", "M",
      gpa=("사 점", "GPA counter → 4.33")),
    L("아이엘츠 팔 점 영.", "M",
      ielts=("팔 점", "IELTS counter → 8.0")),
    L("이제 남은 건 하나였습니다.", "M",
      one=("남은 건", "stats recede")),
    L("어디로 갈 것인가?", "S",
      where=("어디로", "WHERE TO? headline")),
   ]},
  # ------------------------------------------------------------------ 03
  {"id": "s03", "title": "WHAT DO I WANT?", "theme": "light", "lead": 0.9, "tail": 1.0,
   "lines": [
    L("교환학생의 목적은, 사람마다 다를 겁니다.", "M",
      cloud=("사람마다", "6 purpose keywords appear faint")),
    L("어떤 사람은 좋은 학교에서 공부하고 싶을 수도 있고,", "S",
      study=("공부하고", "STUDY highlight")),
    L("영어 실력을 늘리고 싶을 수도 있습니다.", "M",
      english=("영어", "ENGLISH highlight")),
    L("저는 조금 달랐습니다.", "M",
      dim=("저는", "all keywords dim")),
    L("저에게 더 중요했던 건,", "S"),
    L("유럽에서 실제로 살아보는 것.", "M",
      living=("유럽에서", "LIVING ABROAD comes forward")),
    L("그리고 가능하면, 여러 나라를 여행해보는 것.", "M",
      travel=("여러 나라를", "TRAVEL comes forward")),
    L("그래서 영미권 대학 자체를 우선순위로 두기보다는,", "S",
      ukus=("영미권", "UK · US chip"),
      strike=("두기보다는", "strike-through on UK · US")),
    L("유럽에서,", "S",
      map=("유럽에서", "light Europe map + city links")),
    L("어떤 학교가 나에게 가장 잘 맞을까?", "S",
      q=("어떤 학교가", "WHICH SCHOOL FITS ME?")),
    L("이 질문부터 시작했습니다.", "S"),
   ]},
  # ------------------------------------------------------------------ 04
  {"id": "s04", "title": "MY 6 CRITERIA", "theme": "light", "lead": 1.8, "tail": 1.2,
   "lines": [
    L("첫 번째는 위치였습니다.", "M",
      c1=("첫 번째", "rail 01 LOCATION + map panel")),
    L("유럽 여행을 많이 하고 싶었기 때문에,", "S",
      c1_travel=("유럽 여행", "travel arcs")),
    L("단순히 유럽에 있는 것보다, 유럽의 중심에 가까운가를 중요하게 봤습니다.", "M",
      c1_center=("유럽의 중심", "rings around central Europe")),
    L("체코나 독일처럼, 여러 나라와 가까운 지역에 점수를 줬고,", "S",
      c1_czde=("체코나", "Czechia + Germany highlighted"),
      c1_score=("점수를", "+ score tags")),
    L("공항이나 주요 기차역까지 얼마나 걸리는지도 확인했습니다.", "P",
      c1_air=("공항", "airport row"),
      c1_train=("기차역", "train row + travel-time")),
    L("두 번째는, 학교의 수준과 명성.", "M",
      c2=("두 번째", "rail 02 ACADEMIC QUALITY")),
    L("교환학생으로 잠시 다니더라도, 학교 이름은 결국 이력서에 남습니다.", "M",
      c2_cv=("이력서", "CV sheet, education row highlight")),
    L("그래서 큐에스 랭킹 같은 자료를 참고하면서,", "S",
      c2_qs=("큐에스", "QS ranking bars")),
    L("학교의 전반적인 수준과, 전공 관련 경쟁력도 비교했습니다.", "P",
      c2_overall=("전반적인", "OVERALL tag"),
      c2_major=("전공 관련", "BY SUBJECT tag")),
    L("세 번째는 물가.", "M",
      c3=("세 번째", "rail 03 COST OF LIVING")),
    L("교환학생을 가면, 여행 때문에 자연스럽게 돈을 많이 쓰게 됩니다.", "M",
      c3_travel=("여행 때문에", "TRAVEL spend bar rises")),
    L("그래서 적어도 평소 생활하는 곳에서는,", "S",
      c3_living=("평소 생활", "LIVING spend bar")),
    L("조금 더 여유 있게 지낼 수 있는 국가를 선호했습니다.", "P",
      c3_country=("국가를", "country cost comparison")),
    L("그리고 정말 중요하게 본 네 번째 기준.", "M",
      c4=("네 번째", "rail 04 ACADEMIC CALENDAR (accent)")),
    L("바로 아카데믹 캘린더, 학사 일정입니다.", "M",
      c4_title=("아카데믹", "month strip OCT 2026 → DEC 2027")),
    L("유럽 대학은 학교마다, 학기가 시작하고 끝나는 시점이 정말 다릅니다.", "M",
      c4_diff=("시점이", "start/end ticks scatter")),
    L("어떤 학교는 일월에 시작하고,", "S",
      c4_jan=("일월에", "school A bar from JAN")),
    L("어떤 학교는 사월에 시작해서 구월에 끝나기도 합니다.", "M",
      c4_apr=("사월에", "school B bar starts APR"),
      c4_sep=("구월에", "school B bar extends to SEP")),
    L("저는 이천이십육 년 시월 전역 예정이었기 때문에,", "S",
      c4_dis=("이천이십육", "DISCHARGE marker 2026.10")),
    L("전역 후 불필요하게 긴 공백을 만들고 싶지 않았습니다.", "M",
      c4_gap=("긴 공백", "GAP hatch")),
    L("그래서 일월이나 이월에 시작하고,", "S",
      c4_window=("일월이나", "JAN–FEB window")),
    L("한국 복학 일정과 충돌하지 않는 학교를 우선적으로 찾았습니다.", "P",
      c4_skku=("한국 복학", "SKKU fall semester bar"),
      c4_clash=("충돌하지", "A ✓ / B overlap ✕")),
    L("다섯 번째는, 합격 가능성.", "M",
      c5=("다섯 번째", "rail 05 ACCEPTANCE CHANCE")),
    L("에브리타임에서 이전 합격자들에게 직접 물어보고,", "S",
      c5_chat=("에브리타임", "chat bubbles")),
    L("학교 수학보고서도 확인하면서,", "S",
      c5_report=("수학보고서", "study report doc")),
    L("제 성적으로 어느 정도 가능성이 있는지 추정했습니다.", "P",
      c5_gauge=("가능성이", "gauge needle sweeps")),
    L("마지막은 기숙사.", "M",
      c6=("마지막은", "rail 06 DORMITORY")),
    L("해외에서 처음 집을 구하고 계약하는 것보다는,", "S",
      c6_house=("집을 구하고", "contract + house (?)")),
    L("교환학생에게 기숙사를 제공하는 학교를 훨씬 선호했습니다.", "P",
      c6_dorm=("기숙사를", "DORM PROVIDED ✓")),
    L("결국 저에게 중요한 건,", "S",
      end=("결국", "rail + panel clear")),
    L("가장 좋은 학교가 아니라,", "M",
      best=("가장 좋은", "THE BEST SCHOOL")),
    L("나에게 가장 잘 맞는 학교였습니다.", "S",
      forme=("나에게", "≠ THE BEST SCHOOL FOR ME")),
   ]},
  # ------------------------------------------------------------------ 05
  {"id": "s05", "title": "THE SCHOOL HUNT", "theme": "light", "lead": 1.0, "tail": 0.8,
   "lines": [
    L("그런데 기준을 만들었다고 해서, 학교가 바로 정해진 건 아니었습니다.", "M",
      filter=("기준을", "6 criteria chips become a filter row")),
    L("오히려 여기서부터 시작이었습니다.", "M",
      search=("여기서부터", "search bar")),
    L("처음에는,", "S"),
    L("체코 마사릭 유니버시티가 괜찮겠는데? 라고 생각했습니다.", "M",
      mu_map=("체코", "map → Brno"),
      mu=("마사릭", "card MASARYK"),
      mu_ok=("괜찮겠는데", "✓ LOCATION ✓ CALENDAR"),
      mu_hold=("생각했습니다", "ON HOLD → shelf")),
    L("그런데 다시 찾아보니,", "S"),
    L("스페인 아이이 유니버시티도 괜찮은데?", "M",
      ie_map=("스페인", "map → Madrid"),
      ie=("아이이", "card IE UNIVERSITY")),
    L("마드리드에 있고, 학교 수준도 좋아 보였습니다.", "M",
      ie_mad=("마드리드", "✓ MADRID"),
      ie_rep=("학교 수준", "✓ REPUTATION")),
    L("그런데 경영대학 중심이라는 점이 조금 걸렸습니다.", "M",
      ie_x=("경영대학", "✕ MAJOR FIT"),
      ie_out=("걸렸습니다|end", "card → shelf")),
    L("그래서 이번에는, 네덜란드로 눈을 돌렸습니다.", "M",
      nl_map=("네덜란드로", "map → Netherlands")),
    L("브레이어 유니버시테이트 암스테르담이 최고 아닌가?", "M",
      vu=("브레이어", "card VU AMSTERDAM"),
      vu_ok=("최고", "✓ LOCATION ✓ QUALITY")),
    L("그런데 알고 보니,", "M"),
    L("원래 열 명을 뽑던 자리를, 이번에는 한 명으로 줄였더라고요.", "L",
      seats10=("열 명", "SEATS 10"),
      seats1=("한 명", "10 → 1")),
    L("탈락.", "L",
      vu_x=("탈락", "REJECTED stamp")),
    L("그래도 네덜란드가 아쉬워서, 다른 학교들도 찾아봤습니다.", "M",
      vu_out=("그래도", "VU card → shelf"),
      nl_more=("다른 학교들", "search pings around NL")),
    L("그리고 다시 독일.", "M",
      de_map=("독일", "map → Germany")),
    L("엘엠유,", "C",
      lmu=("엘엠유", "card LMU")),
    L("프랑크푸르트 유니버시티 오브 어플라이드 사이언스,", "C",
      fra=("프랑크푸르트", "card FRANKFURT UAS")),
    L("프리 유니버시티 오브 베를린.", "M",
      fub=("프리", "card FU BERLIN")),
    L("그런데 또 문제가 있었습니다.", "M",
      de_prob=("문제가", "cards dim")),
    L("학사 일정.", "M",
      de_cal=("학사", "calendar strip")),
    L("사월에 시작해서 구월에 끝나는 학교들이 많았고,", "S",
      de_apr=("사월에", "bar starts APR"),
      de_sep=("구월에", "bar to SEP")),
    L("그러면 한국 이학기 복학 일정과 겹칠 수 있었습니다.", "L",
      de_skku=("한국", "SKKU fall bar"),
      de_overlap=("겹칠", "overlap flashes")),
    L("또 탈락.", "L",
      de_x=("탈락", "✕ on all three")),
    L("이번에는,", "S",
      de_out=("이번에는", "cards → shelf")),
    L("성적도 괜찮은데, 영국 셰필드를 갈까? 생각했습니다.", "M",
      uk_map=("영국", "map → UK"),
      shf=("셰필드", "card SHEFFIELD"),
      shf_ok=("생각했습니다", "✓ ACADEMIC QUALITY")),
    L("그런데 또 고민이 됐습니다.", "M"),
    L("비싸다.", "M",
      shf_cost=("비싸다", "✕ COST")),
    L("그리고 여행을 많이 하고 싶은 저에게, 영국의 위치도 썩 마음에 들지 않았습니다.", "S",
      shf_loc=("영국의 위치", "✕ TRAVEL ROUTE, channel gap")),
   ]},
  # ------------------------------------------------------------------ 06
  {"id": "s06", "title": "BACK TO MASARYK", "theme": "light", "lead": 1.6, "tail": 1.6,
   "lines": [
    L("그리고 결국,", "L",
      last_=("그리고", "other cards gone; MASARYK left")),
    L("처음부터 후보에 있었던, 마사릭 유니버시티로 다시 돌아왔습니다.", "L",
      back=("마사릭", "MASARYK card → center, turns blue")),
    L("유럽 중앙에 위치해 있고,", "S",
      center=("유럽 중앙", "Brno-centred map, routes; ✓ LOCATION")),
    L("체코의 주요 대학 중 하나이며,", "S",
      quality=("주요 대학", "✓ ACADEMIC QUALITY")),
    L("생활비 부담도 상대적으로 적은 편.", "M",
      cost=("생활비", "✓ COST")),
    L("무엇보다,", "M"),
    L("학사 일정,", "C", cal=("학사", "✓ CALENDAR")),
    L("여행 환경,", "C", trav=("여행", "routes pulse")),
    L("기숙사,", "C", dorm=("기숙사", "✓ DORM")),
    L("그리고 합격 가능성까지.", "M", chance=("합격", "✓ CHANCE")),
    L("제가 중요하게 생각했던 조건들을, 전체적으로 잘 만족했습니다.", "L",
      all6=("전체적으로", "6 / 6")),
    L("그때 깨달았습니다.", "M",
      dim=("그때", "dim")),
    L("결국 중요한 건,", "S"),
    L("가장 좋은 학교가 아니라,", "M",
      best=("가장 좋은", "THE BEST SCHOOL")),
    L("나에게 가장 잘 맞는 학교라는 것.", "S",
      forme=("나에게", "THE BEST SCHOOL FOR ME = MASARYK")),
   ]},
  # ------------------------------------------------------------------ 07
  {"id": "s07", "title": "DEEP DIVE", "theme": "light", "lead": 1.0, "tail": 1.2,
   "lines": [
    L("그래도 한 번 가는 교환학생이고,", "S",
      browser=("그래도", "browser window")),
    L("시간과 비용도 적지 않게 들어가는 만큼, 대충 결정하고 싶지는 않았습니다.", "M",
      time=("시간과", "TIME · COST chips")),
    L("그래서 후보에 있던 학교들의 홈페이지에 들어가서,", "S",
      tabs=("홈페이지", "tabs + URL typing")),
    L("학사 일정,", "C", p_cal=("학사", "ACADEMIC CALENDAR page ✓")),
    L("기숙사,", "C", p_dorm=("기숙사", "DORMITORY page ✓")),
    L("수업,", "C", p_course=("수업", "COURSES page ✓")),
    L("위치,", "C", p_loc=("위치", "BRNO page ✓")),
    L("교환학생 정보까지,", "S", p_ex=("교환학생", "EXCHANGE STUDENTS page ✓")),
    L("가능한 한 하나씩 직접 확인했습니다.", "M",
      done=("하나씩", "checklist complete")),
    L("덕분에 지금은, 적어도 이렇게 말할 수 있을 것 같습니다.", "M",
      out=("덕분에", "browser recedes")),
    L("그래도 그때의 최선은, 마사릭 유니버시티였다.", "S",
      q1=("그때의", "quote line 1"),
      q2=("마사릭", "quote line 2 MASARYK UNIVERSITY")),
   ]},
  # ------------------------------------------------------------------ 08
  {"id": "s08", "title": "APPLICATION", "theme": "light", "lead": 1.0, "tail": 1.4,
   "lines": [
    L("성균관대학교 교환학생 선발은, 일차와 이차로 나뉘어 진행됩니다.", "M",
      app=("성균관대학교", "APPLICATION node"),
      r1=("일차와", "1ST ROUND"),
      r2=("이차로", "2ND ROUND")),
    L("가능하면 일차에서 합격하는 것이 좋다고 생각했고,", "S",
      r1f=("일차에서", "1ST ROUND focus")),
    L("마사릭 유니버시티에 다녀온 지인과, 에브리타임의 선배들에게 직접 물어봤습니다.", "M",
      mu=("마사릭", "MASARYK target"),
      ask=("지인과", "people / chat")),
    L("그리고 제 성적이면, 어느 정도 안정권이라고 판단했습니다.", "M",
      safe=("안정권", "gauge → safe zone")),
    L("하지만 선발 인원은,", "Q",
      but=("하지만", "clear for numbers")),
    L("두 명.", "M", seats=("두 명", "2 SEATS")),
    L("지원자는 약,", "Q"),
    L("여섯 명.", "Q", apps=("여섯", "~6 APPLICANTS")),
    L("아무리 제 성적이 괜찮아도,", "S"),
    L("적은 인원을 뽑는 학교는, 마지막까지 긴장할 수밖에 없었습니다.", "S",
      tense=("긴장할", "tension pulse; darken")),
   ]},
  # ------------------------------------------------------------------ 09
  {"id": "s09", "title": "THE RESULT", "theme": "dark", "lead": 1.2, "tail": 2.0,
   "lines": [
    L("그리고 합격 발표 날.", "M",
      day=("합격 발표", "RESULT DAY")),
    L("평일이라, 군대에서 휴대폰을 받자마자 바로 결과를 확인했습니다.", "L",
      phone=("휴대폰을", "phone slides in, screen on"),
      check=("결과를", "EXCHANGE RESULT screen")),
    L("그리고...", "X",
      tap=("그리고", "tap; everything freezes")),
    L("합격.", "L",
      pass_=("합격", "1지망 합격")),
    L("일 지망이었던 마사릭 유니버시티에 최종 합격했습니다.", "M",
      logo=("마사릭", "MASARYK UNIVERSITY logo"),
      final=("최종", "1ST CHOICE · ACCEPTED")),
    L("아직은 조금 실감이 안 나지만,", "S"),
    L("이천이십칠 년 일 학기.", "M",
      y=("이천이십칠", "2027-1")),
    L("저는 체코 브르노에서 한 학기를 보내게 됩니다.", "S",
      brno=("브르노", "BRNO, CZECH REPUBLIC")),
   ]},
  # ------------------------------------------------------------------ 10
  {"id": "s10", "title": "TWO TIPS", "theme": "light", "lead": 1.0, "tail": 1.4,
   "lines": [
    L("마지막으로, 교환학생을 준비하면서 제가 직접 느낀 팁 두 가지를 말씀드리겠습니다.", "L",
      tips=("두 가지", "2 TIPS")),
    L("첫 번째.", "M", t1=("첫 번째", "01 ASK")),
    L("정말 가고 싶은 학교라면, 직접 문의해보세요.", "M",
      t1_sub=("직접 문의", "직접 문의해보세요")),
    L("저도 프랑크푸르트 유니버시티 오브 어플라이드 사이언스에 관심이 있었는데,", "S",
      fra=("프랑크푸르트", "FRANKFURT UAS card")),
    L("당시에는 세 개 학기 이상 수료해야 한다고 적혀 있었습니다.", "M",
      req=("세 개 학기", "REQUIRED 3+ SEMESTERS")),
    L("저는 두 개 학기만 수료한 상태였지만,", "S",
      me=("두 개 학기", "ME 2 SEMESTERS ✕")),
    L("혹시나 하는 마음에 직접 이메일을 보냈습니다.", "M",
      mail=("이메일을", "email sent")),
    L("그리고 학교에서는, 제 상황이면 지원해도 괜찮다는 답변을 받았습니다.", "M",
      reply=("지원해도", "reply ✓ OK TO APPLY")),
    L("결국 학사 일정 때문에 실제 지원까지 하지는 않았지만,", "S",
      noapply=("학사 일정", "note: calendar")),
    L("이 경험을 통해 한 가지를 배웠습니다.", "M"),
    L("홈페이지에 적힌 기준만 보고, 미리 포기할 필요는 없다는 것.", "M",
      lesson=("미리 포기할", "lesson line")),
    L("물론 모든 학교가 예외를 인정해주는 것은 아닙니다.", "M",
      caveat=("물론", "caveat")),
    L("하지만 정말 가고 싶은 학교라면, 한 번쯤 직접 물어보는 것도 좋은 방법입니다.", "L",
      ask=("직접 물어보는", "ASK.")),
    L("두 번째.", "M", t2=("두 번째", "02 CHECK THE CALENDAR")),
    L("아카데믹 캘린더는 반드시 확인하세요.", "M",
      t2_sub=("반드시", "반드시 확인")),
    L("학교 이름이나 도시만 보고 선택하지 말고,", "S",
      names=("학교 이름", "NAME · CITY chips fade")),
    L("이 학교에서 한 학기를 마치고 돌아왔을 때,", "S",
      ex=("한 학기를", "exchange bar"),
      ret=("돌아왔을", "return arrow")),
    L("한국에서 정상적으로 다음 학기를 시작할 수 있는가?", "M",
      next=("다음 학기", "SKKU next semester ✓")),
    L("여기까지 확인해야 합니다.", "S",
      ok=("여기까지", "✓")),
   ]},
  # ------------------------------------------------------------------ 11
  {"id": "s11", "title": "CLOSING", "theme": "dark", "lead": 1.4, "tail": 3.6,
   "lines": [
    L("결국 교환학생을 준비하면서, 제가 느낀 건 하나였습니다.", "M",
      map=("결국", "dark Europe map, Brno")),
    L("좋은 학교를 찾는 것보다,", "S",
      good=("좋은 학교", "'좋은 학교' (faint)")),
    L("나에게 맞는 학교를 찾는 것이 더 중요하다는 것.", "L",
      fit=("나에게", "'나에게 맞는 학교' (bright)")),
    L("저에게는,", "S", list=("저에게는", "clear text")),
    L("유럽 여행,", "C", k1=("유럽", "TRAVEL + routes")),
    L("생활비,", "C", k2=("생활비", "COST")),
    L("위치,", "C", k3=("위치", "LOCATION")),
    L("학사 일정,", "C", k4=("학사", "CALENDAR")),
    L("학교 수준,", "C", k5=("학교", "QUALITY")),
    L("기숙사,", "C", k6=("기숙사", "DORM")),
    L("그리고 합격 가능성까지.", "M", k7=("합격", "CHANCE")),
    L("이 모든 것을 고려했을 때,", "S",
      converge=("고려했을", "tags converge into Brno")),
    L("마사릭 유니버시티가 가장 잘 맞았습니다.", "L",
      mu=("마사릭", "MASARYK UNIVERSITY at Brno")),
    L("이제 남은 건 하나입니다.", "L",
      last=("남은 건", "map fades")),
    L("이천이십칠 년 일 학기.", "L",
      y=("이천이십칠", "2027-1"),
      lockup=("일 학기|end", "MASARYK UNIVERSITY / BRNO, CZECH REPUBLIC")),
    L("Let's go, 마사릭!", "S",
      go=("Let", "LET'S GO MASARYK!")),
   ]},
]


def tts_text(scene):
    out = []
    for i, ln in enumerate(scene["lines"]):
        last = i == len(scene["lines"]) - 1
        out.append(ln["tts"] + ("" if last else TTS_TAG[ln["pause"]]))
    return "\n".join(out)


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    for sc in SCENES:
        for i, ln in enumerate(sc["lines"]):
            ln["id"] = f"{sc['id']}_l{i+1:02d}"
            for cid, (anchor, _) in ln["cues"].items():
                a = anchor.split("|")[0]
                assert a in ln["tts"], (sc["id"], cid, anchor)
        sc["tts_text"] = tts_text(sc)
    json.dump({"voice": VOICE, "pauses": PAUSES, "pronunciation": PRONUNCIATION, "scenes": SCENES},
              open(os.path.join(here, "segments.json"), "w"), ensure_ascii=False, indent=1)
    total = sum(len(l["tts"]) for s in SCENES for l in s["lines"])
    print("scenes", len(SCENES), "lines", sum(len(s["lines"]) for s in SCENES), "chars", total)
